### PR TITLE
Move metadata to pyproject.toml

### PR DESCRIPTION
**Pull request by cdce8p**
Move the static metadata to `pyproject.toml` and delete `setup.py`. The metadata diff
```diff
 Name: accuweather
 Version: 4.0.0
 Summary: Python wrapper for getting weather data from AccuWeather API.
 Author: Maciej Bieniek
 License: Apache-2.0
-Home-page: https://github.com/bieniu/accuweather
+Project-URL: Homepage, https://github.com/bieniu/accuweather
 Classifier: Development Status :: 5 - Production/Stable
 Classifier: License :: OSI Approved :: Apache Software License
 Classifier: Operating System :: OS Independent
 Classifier: Programming Language :: Python
 Classifier: Programming Language :: Python :: 3
 Classifier: Programming Language :: Python :: 3.12
 Classifier: Programming Language :: Python :: 3.13
 Classifier: Programming Language :: Python :: 3 :: Only
 Classifier: Typing :: Typed
 Requires-Python: >=3.12
 Description-Content-Type: text/markdown
 License-File: LICENSE
 Requires-Dist: aiohttp>=3.9.4
 Requires-Dist: orjson

 ...
```

Some notes:
- `include_package_data=True` this is automatically set for metadata in pyproject.toml
- `package_data={"accuweather": ["py.typed"]}` also auto-included by setuptools
- `packages=["accuweather"]` was changed to `tool.setuptools.packages.find.include = ["accuweather*"]`. Note the `*` suffix to match potential sub-packages if they are ever added.
- The requirements are specified both in `project.dependencies` and `requirements.txt`. _The latter is probably not necessary and could be removed._

### CODE REVIEW

**Comment by bieniu** [comment]
I saw your PR, thank you 🙏 I'll be home tomorrow and take care of it.

**Comment by cdce8p** [comment]
> I saw your PR, thank you 🙏 I'll be home tomorrow and take care of it.

No worries. Just wasn't sure if you've seen it.

**Review by bieniu — APPROVED** [review]
Looks good, thanks @cdce8p 👍

**Pull request merged**
